package net.satisfy.farm_and_charm.neoforge.core.config;

import net.neoforged.fml.event.config.ModConfigEvent;
import net.neoforged.neoforge.common.ModConfigSpec;

public class FarmAndCharmNeoForgeConfig {
    public static final ModConfigSpec COMMON_CONFIG;
    public static final ModConfigSpec.BooleanValue ENABLE_RAIN_GROWTH_EFFECT;
    public static final ModConfigSpec.BooleanValue ENABLE_FIREFLIES;
    public static final ModConfigSpec.DoubleValue RAIN_GROWTH_MULTIPLIER;
    public static final ModConfigSpec.IntValue BIG_CROP_CHANCE;
    public static final ModConfigSpec.BooleanValue ENABLE_BONEMEAL_EFFECT;
    public static final ModConfigSpec.BooleanValue ENABLE_FERTILIZER;
    public static final ModConfigSpec.IntValue FERTILIZED_SOIL_RANGE;
    public static final ModConfigSpec.IntValue SCARECROW_GROWTH_INTERVAL;
    public static final ModConfigSpec.IntValue SCARECROW_RANGE;
    public static final ModConfigSpec.IntValue WILD_CROP_DROP_CHANCE;
    public static final ModConfigSpec.IntValue WATER_SPRINKLER_RANGE;
    public static final ModConfigSpec.IntValue WELL_GROUNDWATER_DEPTH;
    public static final ModConfigSpec.IntValue WELL_RAIN_FILL_CHANCE;
    public static final ModConfigSpec.IntValue FEEDING_TROUGH_RANGE;
    public static final ModConfigSpec.BooleanValue ENABLE_DOG_FOOD_TAMING;
    public static final ModConfigSpec.BooleanValue ENABLE_CAT_TAMING_CHANCE;
    public static final ModConfigSpec.BooleanValue ENABLE_HORSE_TAMING;
    public static final ModConfigSpec.BooleanValue ENABLE_HORSE_EFFECTS;
    public static final ModConfigSpec.BooleanValue ENABLE_CHICKEN_EFFECTS;
    public static final ModConfigSpec.IntValue CHICKEN_COOP_MAX_CHICKENS;
    public static final ModConfigSpec.IntValue CHICKEN_COOP_MAX_EGGS;
    public static final ModConfigSpec.BooleanValue ENABLE_DOG_BEGGING;
    public static final ModConfigSpec.BooleanValue ENABLE_CAT_BEGGING;
    public static final ModConfigSpec.IntValue PET_BOWL_SEARCH_RANGE;
    public static final ModConfigSpec.IntValue FEEDING_TIME_MIDDAY_START;
    public static final ModConfigSpec.IntValue FEEDING_TIME_MIDDAY_END;
    public static final ModConfigSpec.IntValue FEEDING_TIME_EVENING_START;
    public static final ModConfigSpec.IntValue FEEDING_TIME_EVENING_END;
    public static final ModConfigSpec.IntValue IRON_CLEAVER_CHOPS;
    public static final ModConfigSpec.IntValue DIAMOND_CLEAVER_CHOPS;
    public static final ModConfigSpec.IntValue NETHERITE_CLEAVER_CHOPS;
    public static final ModConfigSpec.BooleanValue CLEAVER_HEAD_DROPS;
    public static final ModConfigSpec.BooleanValue COOKING_EXPERIENCE;
    public static final ModConfigSpec.DoubleValue COOKING_EXPERIENCE_MULTIPLIER;
    public static final ModConfigSpec.BooleanValue ANIMATIONS;
    public static final ModConfigSpec.BooleanValue SHOW_CUTTING_BOARD_INFO;
    public static final ModConfigSpec.BooleanValue SHOW_MINCER_INFO;
    public static final ModConfigSpec.BooleanValue SHOW_CRAFTING_BOWL_INFO;
    public static final ModConfigSpec.BooleanValue SHOW_SILO_INFO;
    public static final ModConfigSpec.BooleanValue SHOW_WATER_SPRINKLER_INFO;
    public static final ModConfigSpec.BooleanValue SHOW_SCARECROW_INFO;
    public static final ModConfigSpec.BooleanValue INFO_TOOLTIPS_NEED_DUNGAREES;
    public static final ModConfigSpec.IntValue CHICKEN_EFFECT_TICK_INTERVAL;
    public static final ModConfigSpec.IntValue CHICKEN_EFFECT_EGG_CHANCE;
    public static final ModConfigSpec.IntValue CHICKEN_EFFECT_FEATHER_CHANCE;
    public static final ModConfigSpec.IntValue FEAST_EFFECT_SATIATION_INTERVAL;
    public static final ModConfigSpec.IntValue FEAST_EFFECT_SUSTENANCE_INTERVAL;
    public static final ModConfigSpec.IntValue FEAST_EFFECT_HEAL_AMOUNT;
    public static final ModConfigSpec.IntValue SUSTENANCE_EFFECT_INTERVAL;
    public static final ModConfigSpec.IntValue SUSTENANCE_EFFECT_HEAL_AMOUNT;
    public static final ModConfigSpec.IntValue SUSTENANCE_EFFECT_FOOD_INCREMENT;
    public static final ModConfigSpec.IntValue SATIATION_EFFECT_INTERVAL;
    public static final ModConfigSpec.IntValue SATIATION_EFFECT_HEAL_AMOUNT;
    public static final ModConfigSpec.IntValue OAT_PANCAKE_NUTRITION;
    public static final ModConfigSpec.DoubleValue OAT_PANCAKE_SATURATION_MOD;
    public static final ModConfigSpec.IntValue ROASTED_CORN_NUTRITION;
    public static final ModConfigSpec.DoubleValue ROASTED_CORN_SATURATION_MOD;
    public static final ModConfigSpec.IntValue POTATO_WITH_ROAST_MEAT_NUTRITION;
    public static final ModConfigSpec.DoubleValue POTATO_WITH_ROAST_MEAT_SATURATION_MOD;
    public static final ModConfigSpec.IntValue BAKED_LAMB_HAM_NUTRITION;
    public static final ModConfigSpec.DoubleValue BAKED_LAMB_HAM_SATURATION_MOD;
    public static final ModConfigSpec.IntValue FARMERS_BREAKFAST_NUTRITION;
    public static final ModConfigSpec.DoubleValue FARMERS_BREAKFAST_SATURATION_MOD;
    public static final ModConfigSpec.IntValue STUFFED_CHICKEN_NUTRITION;
    public static final ModConfigSpec.DoubleValue STUFFED_CHICKEN_SATURATION_MOD;
    public static final ModConfigSpec.IntValue STUFFED_RABBIT_NUTRITION;
    public static final ModConfigSpec.DoubleValue STUFFED_RABBIT_SATURATION_MOD;
    public static final ModConfigSpec.IntValue GRANDMOTHERS_STRAWBERRY_CAKE_NUTRITION;
    public static final ModConfigSpec.DoubleValue GRANDMOTHERS_STRAWBERRY_CAKE_SATURATION_MOD;
    public static final ModConfigSpec.IntValue FARMERS_BREAD_NUTRITION;
    public static final ModConfigSpec.DoubleValue FARMERS_BREAD_SATURATION_MOD;
    public static final ModConfigSpec.IntValue FARMER_SALAD_NUTRITION;
    public static final ModConfigSpec.DoubleValue FARMER_SALAD_SATURATION_MOD;
    public static final ModConfigSpec.IntValue GOULASH_NUTRITION;
    public static final ModConfigSpec.DoubleValue GOULASH_SATURATION_MOD;
    public static final ModConfigSpec.IntValue SIMPLE_TOMATO_SOUP_NUTRITION;
    public static final ModConfigSpec.DoubleValue SIMPLE_TOMATO_SOUP_SATURATION_MOD;
    public static final ModConfigSpec.IntValue BARLEY_SOUP_NUTRITION;
    public static final ModConfigSpec.DoubleValue BARLEY_SOUP_SATURATION_MOD;
    public static final ModConfigSpec.IntValue ONION_SOUP_NUTRITION;
    public static final ModConfigSpec.DoubleValue ONION_SOUP_SATURATION_MOD;
    public static final ModConfigSpec.IntValue POTATO_SOUP_NUTRITION;
    public static final ModConfigSpec.DoubleValue POTATO_SOUP_SATURATION_MOD;
    public static final ModConfigSpec.IntValue PASTA_WITH_ONION_SAUCE_NUTRITION;
    public static final ModConfigSpec.DoubleValue PASTA_WITH_ONION_SAUCE_SATURATION_MOD;
    public static final ModConfigSpec.IntValue CORN_GRITS_NUTRITION;
    public static final ModConfigSpec.DoubleValue CORN_GRITS_SATURATION_MOD;
    public static final ModConfigSpec.IntValue OATMEAL_WITH_STRAWBERRIES_NUTRITION;
    public static final ModConfigSpec.DoubleValue OATMEAL_WITH_STRAWBERRIES_SATURATION_MOD;
    public static final ModConfigSpec.IntValue SAUSAGE_WITH_OAT_PATTY_NUTRITION;
    public static final ModConfigSpec.DoubleValue SAUSAGE_WITH_OAT_PATTY_SATURATION_MOD;
    public static final ModConfigSpec.IntValue LAMB_WITH_CORN_NUTRITION;
    public static final ModConfigSpec.DoubleValue LAMB_WITH_CORN_SATURATION_MOD;
    public static final ModConfigSpec.IntValue BEEF_PATTY_WITH_VEGETABLES_NUTRITION;
    public static final ModConfigSpec.DoubleValue BEEF_PATTY_WITH_VEGETABLES_SATURATION_MOD;
    public static final ModConfigSpec.IntValue BARLEY_PATTIES_WITH_POTATOES_NUTRITION;
    public static final ModConfigSpec.DoubleValue BARLEY_PATTIES_WITH_POTATOES_SATURATION_MOD;
    public static final ModConfigSpec.IntValue BACON_WITH_EGGS_NUTRITION;
    public static final ModConfigSpec.DoubleValue BACON_WITH_EGGS_SATURATION_MOD;
    public static final ModConfigSpec.IntValue CHICKEN_WRAPPED_IN_BACON_NUTRITION;
    public static final ModConfigSpec.DoubleValue CHICKEN_WRAPPED_IN_BACON_SATURATION_MOD;
    public static final ModConfigSpec.IntValue COOKED_SALMON_NUTRITION;
    public static final ModConfigSpec.DoubleValue COOKED_SALMON_SATURATION_MOD;
    public static final ModConfigSpec.IntValue COOKED_COD_NUTRITION;
    public static final ModConfigSpec.DoubleValue COOKED_COD_SATURATION_MOD;
    public static final ModConfigSpec.IntValue ROASTED_CHICKEN_NUTRITION;
    public static final ModConfigSpec.DoubleValue ROASTED_CHICKEN_SATURATION_MOD;

    public static boolean enableRainGrowthEffect = true;
    public static boolean enableFireflies = true;
    public static double rainGrowthMultiplier = 0.5;
    public static int bigCropChance = 3;
    public static boolean enableBonemealEffect = true;
    public static boolean enableFertilizer = true;
    public static int fertilizedSoilRange = 5;
    public static int scarecrowGrowthInterval = 25;
    public static int scarecrowRange = 8;
    public static int wildCropDropChance = 60;
    public static int waterSprinklerRange = 8;
    public static int wellGroundwaterDepth = 6;
    public static int wellRainFillChance = 17;
    public static int feedingTroughRange = 8;
    public static boolean enableDogFoodTaming = true;
    public static boolean enableCatTamingChance = true;
    public static boolean enableHorseTaming = true;
    public static boolean enableHorseEffects = true;
    public static boolean enableChickenEffects = true;
    public static int chickenCoopMaxChickens = 3;
    public static int chickenCoopMaxEggs = 9;
    public static boolean enableDogBegging = true;
    public static boolean enableCatBegging = true;
    public static int petBowlSearchRange = 16;
    public static int feedingTimeMiddayStart = 5800;
    public static int feedingTimeMiddayEnd = 6200;
    public static int feedingTimeEveningStart = 11500;
    public static int feedingTimeEveningEnd = 12500;
    public static int ironCleaverChops = 5;
    public static int diamondCleaverChops = 3;
    public static int netheriteCleaverChops = 1;
    public static boolean cleaverHeadDrops = true;
    public static boolean cookingExperience = true;
    public static float cookingExperienceMultiplier = 1.0f;
    public static boolean animations = true;
    public static boolean showCuttingBoardInfo = true;
    public static boolean showMincerInfo = true;
    public static boolean showCraftingBowlInfo = true;
    public static boolean showSiloInfo = true;
    public static boolean showWaterSprinklerInfo = true;
    public static boolean showScarecrowInfo = true;
    public static boolean infoTooltipsNeedDungarees = false;
    public static int chickenEffectTickInterval = 120;
    public static int chickenEffectEggChance = 20;
    public static int chickenEffectFeatherChance = 20;
    public static int feastEffectSatiationInterval = 40;
    public static int feastEffectSustenanceInterval = 200;
    public static int feastEffectHealAmount = 1;
    public static int sustenanceEffectInterval = 200;
    public static int sustenanceEffectHealAmount = 1;
    public static int sustenanceEffectFoodIncrement = 1;
    public static int satiationEffectInterval = 40;
    public static int satiationEffectHealAmount = 1;
    public static int oatPancakeNutrition = 5;
    public static double oatPancakeSaturationMod = 0.6;
    public static int roastedCornNutrition = 5;
    public static double roastedCornSaturationMod = 0.5;
    public static int potatoWithRoastMeatNutrition = 7;
    public static double potatoWithRoastMeatSaturationMod = 0.7;
    public static int bakedLambHamNutrition = 8;
    public static double bakedLambHamSaturationMod = 0.9;
    public static int farmersBreakfastNutrition = 12;
    public static double farmersBreakfastSaturationMod = 1.2;
    public static int stuffedChickenNutrition = 8;
    public static double stuffedChickenSaturationMod = 0.8;
    public static int stuffedRabbitNutrition = 9;
    public static double stuffedRabbitSaturationMod = 0.9;
    public static int grandmothersStrawberryCakeNutrition = 4;
    public static double grandmothersStrawberryCakeSaturationMod = 0.7;
    public static int farmersBreadNutrition = 6;
    public static double farmersBreadSaturationMod = 0.8;
    public static int farmerSaladNutrition = 7;
    public static double farmerSaladSaturationMod = 0.6;
    public static int goulashNutrition = 8;
    public static double goulashSaturationMod = 0.9;
    public static int simpleTomatoSoupNutrition = 6;
    public static double simpleTomatoSoupSaturationMod = 0.6;
    public static int barleySoupNutrition = 5;
    public static double barleySoupSaturationMod = 0.8;
    public static int onionSoupNutrition = 7;
    public static double onionSoupSaturationMod = 0.6;
    public static int potatoSoupNutrition = 5;
    public static double potatoSoupSaturationMod = 0.6;
    public static int pastaWithOnionSauceNutrition = 6;
    public static double pastaWithOnionSauceSaturationMod = 0.7;
    public static int cornGritsNutrition = 6;
    public static double cornGritsSaturationMod = 0.5;
    public static int oatmealWithStrawberriesNutrition = 4;
    public static double oatmealWithStrawberriesSaturationMod = 0.8;
    public static int sausageWithOatPattyNutrition = 8;
    public static double sausageWithOatPattySaturationMod = 0.9;
    public static int lambWithCornNutrition = 8;
    public static double lambWithCornSaturationMod = 0.8;
    public static int beefPattyWithVegetablesNutrition = 6;
    public static double beefPattyWithVegetablesSaturationMod = 0.8;
    public static int barleyPattiesWithPotatoesNutrition = 5;
    public static double barleyPattiesWithPotatoesSaturationMod = 0.9;
    public static int baconWithEggsNutrition = 6;
    public static double baconWithEggsSaturationMod = 0.7;
    public static int chickenWrappedInBaconNutrition = 9;
    public static double chickenWrappedInBaconSaturationMod = 0.9;
    public static int cookedSalmonNutrition = 7;
    public static double cookedSalmonSaturationMod = 0.9;
    public static int cookedCodNutrition = 7;
    public static double cookedCodSaturationMod = 0.9;
    public static int roastedChickenNutrition = 5;
    public static double roastedChickenSaturationMod = 0.8;

    static {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();
        builder.comment("Everything about growing crops.").push("Farming");
        ENABLE_RAIN_GROWTH_EFFECT = builder.comment("Crops grow faster while it is raining on them.").define("enableRainGrowthEffect", true);
        ENABLE_FIREFLIES = builder.comment("Shows fireflies at night above wild rice and around lit lanterns outdoors.").define("enableFireflies", true);
        RAIN_GROWTH_MULTIPLIER = builder.comment("How much faster crops grow in rain. 0.5 = 50% faster, 1.0 = twice as fast.").defineInRange("rainGrowthMultiplier", 0.5, 0.0, 2.0);
        BIG_CROP_CHANCE = builder.comment("Chance in percent that a fully grown lettuce or onion turns into a giant crop during rain.").defineInRange("bigCropChance", 3, 0, 100);
        ENABLE_BONEMEAL_EFFECT = builder.comment("Fertilized farmland occasionally acts like bone meal on the crop above it.").define("enableBonemealEffect", true);
        ENABLE_FERTILIZER = builder.comment("Allows using fertilizer on blocks.").define("enableFertilizer", true);
        FERTILIZED_SOIL_RANGE = builder.comment("Radius in blocks in which fertilized soil helps nearby plants grow.").defineInRange("fertilizedSoilRange", 5, 1, 16);
        SCARECROW_GROWTH_INTERVAL = builder.comment("Every how many seconds a scarecrow helps the crops around it grow.").defineInRange("scarecrowGrowthInterval", 25, 1, 600);
        SCARECROW_RANGE = builder.comment("Radius in blocks around the scarecrow.").defineInRange("scarecrowRange", 8, 1, 16);
        WILD_CROP_DROP_CHANCE = builder.comment("Chance in percent that bone meal on a wild crop drops another wild crop.").defineInRange("wildCropDropChance", 60, 0, 100);
        builder.pop();

        builder.comment("Sprinklers and the timber well.").push("Water");
        WATER_SPRINKLER_RANGE = builder.comment("Radius in blocks that a water sprinkler keeps watered.").defineInRange("waterSprinklerRange", 8, 1, 16);
        WELL_GROUNDWATER_DEPTH = builder.comment("How many blocks below the well it searches for a water source.").defineInRange("wellGroundwaterDepth", 6, 1, 32);
        WELL_RAIN_FILL_CHANCE = builder.comment("Chance in percent per random tick that rain fills the well a bit.").defineInRange("wellRainFillChance", 17, 0, 100);
        builder.pop();

        builder.comment("Feeding, taming and animal behaviour.").push("Animals");
        FEEDING_TROUGH_RANGE = builder.comment("How far animals walk to eat from a feeding trough or drink from a water trough.").defineInRange("feedingTroughRange", 8, 1, 16);
        ENABLE_DOG_FOOD_TAMING = builder.comment("Wolves can be tamed with dog food.").define("enableDogFoodTaming", true);
        ENABLE_CAT_TAMING_CHANCE = builder.comment("Cats can be tamed with cat food.").define("enableCatTamingChance", true);
        ENABLE_HORSE_TAMING = builder.comment("Horses can be tamed with horse fodder.").define("enableHorseTaming", true);
        ENABLE_HORSE_EFFECTS = builder.comment("Horse fodder heals horses and gives them a temporary boost.").define("enableHorseEffects", true);
        ENABLE_CHICKEN_EFFECTS = builder.comment("Chicken feed makes chickens lay eggs and drop feathers more often.").define("enableChickenEffects", true);
        CHICKEN_COOP_MAX_CHICKENS = builder.comment("How many chickens fit into one chicken coop.").defineInRange("chickenCoopMaxChickens", 3, 1, 16);
        CHICKEN_COOP_MAX_EGGS = builder.comment("How many eggs a chicken coop can hold before you collect them.").defineInRange("chickenCoopMaxEggs", 9, 1, 64);
        ENABLE_DOG_BEGGING = builder.comment("Tamed dogs sit at their empty pet bowl at feeding time and whine.").define("enableDogBegging", true);
        ENABLE_CAT_BEGGING = builder.comment("Tamed cats sit at their empty pet bowl at feeding time and meow.").define("enableCatBegging", true);
        PET_BOWL_SEARCH_RANGE = builder.comment("How far pets look for their bowl at feeding time. Higher values cost more performance.").defineInRange("petBowlSearchRange", 16, 4, 32);
        FEEDING_TIME_MIDDAY_START = builder.comment("Time of day in ticks. 0 = sunrise, 6000 = noon, 12000 = sunset, 18000 = midnight.").defineInRange("feedingTimeMiddayStart", 5800, 0, 23999);
        FEEDING_TIME_MIDDAY_END = builder.comment("Time of day in ticks. 0 = sunrise, 6000 = noon, 12000 = sunset, 18000 = midnight.").defineInRange("feedingTimeMiddayEnd", 6200, 0, 23999);
        FEEDING_TIME_EVENING_START = builder.comment("Time of day in ticks. 0 = sunrise, 6000 = noon, 12000 = sunset, 18000 = midnight.").defineInRange("feedingTimeEveningStart", 11500, 0, 23999);
        FEEDING_TIME_EVENING_END = builder.comment("Time of day in ticks. 0 = sunrise, 6000 = noon, 12000 = sunset, 18000 = midnight.").defineInRange("feedingTimeEveningEnd", 12500, 0, 23999);
        builder.pop();

        builder.comment("Cutting board and cleavers.").push("Kitchen");
        IRON_CLEAVER_CHOPS = builder.comment("How many chops an iron cleaver needs per ingredient.").defineInRange("ironCleaverChops", 5, 1, 20);
        DIAMOND_CLEAVER_CHOPS = builder.comment("How many chops a diamond cleaver needs per ingredient.").defineInRange("diamondCleaverChops", 3, 1, 20);
        NETHERITE_CLEAVER_CHOPS = builder.comment("How many chops a netherite cleaver needs per ingredient.").defineInRange("netheriteCleaverChops", 1, 1, 20);
        CLEAVER_HEAD_DROPS = builder.comment("Mobs killed with a cleaver can drop their head.").define("cleaverHeadDrops", true);
        COOKING_EXPERIENCE = builder.comment("Cooking, mincing, cutting, stripping and whisking give experience. The amount per recipe is set in the recipe files.").define("cookingExperience", true);
        COOKING_EXPERIENCE_MULTIPLIER = builder.comment("Multiplies all experience from cooking and food processing. 1.0 = as set in the recipes.").defineInRange("cookingExperienceMultiplier", 1.0, 0.0, 10.0);
        ANIMATIONS = builder.comment("Blocks of this mod are animated.").define("animations", true);
        builder.pop();

        builder.comment("Info tooltips that appear when looking at a block. Only affects your own screen.").push("Info Tooltips");
        SHOW_CUTTING_BOARD_INFO = builder.comment("Shows an info tooltip when looking at the cutting board.").define("showCuttingBoardInfo", true);
        SHOW_MINCER_INFO = builder.comment("Shows an info tooltip when looking at the mincer.").define("showMincerInfo", true);
        SHOW_CRAFTING_BOWL_INFO = builder.comment("Shows an info tooltip when looking at the crafting bowl.").define("showCraftingBowlInfo", true);
        SHOW_SILO_INFO = builder.comment("Shows an info tooltip when looking at the silo.").define("showSiloInfo", true);
        SHOW_WATER_SPRINKLER_INFO = builder.comment("Shows an info tooltip when looking at the water sprinkler.").define("showWaterSprinklerInfo", true);
        SHOW_SCARECROW_INFO = builder.comment("Shows an info tooltip when looking at the scarecrow.").define("showScarecrowInfo", true);
        INFO_TOOLTIPS_NEED_DUNGAREES = builder.comment("Info tooltips only show while wearing Dungarees.").define("needDungarees", false);
        builder.pop();

        builder.comment("Fine-tuning of the food effects.").push("Effects");
        builder.push("Chicken Effect");
        CHICKEN_EFFECT_TICK_INTERVAL = builder.comment("Every how many ticks the effect tries to drop an egg or feather. 20 ticks = 1 second.").defineInRange("chickenEffectTickInterval", 120, 10, 600);
        CHICKEN_EFFECT_EGG_CHANCE = builder.comment("Chance in percent to drop an egg.").defineInRange("chickenEffectEggChance", 20, 0, 100);
        CHICKEN_EFFECT_FEATHER_CHANCE = builder.comment("Chance in percent to drop a feather.").defineInRange("chickenEffectFeatherChance", 20, 0, 100);
        builder.pop();
        builder.push("Feast Effect");
        FEAST_EFFECT_SATIATION_INTERVAL = builder.comment("Every how many ticks you heal while full. 20 ticks = 1 second.").defineInRange("feastEffectSatiationInterval", 40, 10, 200);
        FEAST_EFFECT_SUSTENANCE_INTERVAL = builder.comment("Every how many ticks one hunger point is restored. 20 ticks = 1 second.").defineInRange("feastEffectSustenanceInterval", 200, 50, 600);
        FEAST_EFFECT_HEAL_AMOUNT = builder.comment("Health points healed each time. 2 points = 1 heart.").defineInRange("feastEffectHealAmount", 1, 1, 5);
        builder.pop();
        builder.push("Sustenance Effect");
        SUSTENANCE_EFFECT_INTERVAL = builder.comment("Every how many ticks the effect kicks in. 20 ticks = 1 second.").defineInRange("sustenanceEffectInterval", 200, 50, 600);
        SUSTENANCE_EFFECT_HEAL_AMOUNT = builder.comment("Health points healed when your hunger bar is full. 2 points = 1 heart.").defineInRange("sustenanceEffectHealAmount", 1, 1, 5);
        SUSTENANCE_EFFECT_FOOD_INCREMENT = builder.comment("Hunger points restored when you are not full.").defineInRange("sustenanceEffectFoodIncrement", 1, 1, 20);
        builder.pop();
        builder.push("Satiation Effect");
        SATIATION_EFFECT_INTERVAL = builder.comment("Every how many ticks you heal while full. 20 ticks = 1 second.").defineInRange("satiationEffectInterval", 40, 10, 200);
        SATIATION_EFFECT_HEAL_AMOUNT = builder.comment("Health points healed each time. 2 points = 1 heart.").defineInRange("satiationEffectHealAmount", 1, 1, 5);
        builder.pop();
        builder.pop();

        builder.comment("Hunger and saturation of the food items. Changes need a game restart.").push("Food");
        OAT_PANCAKE_NUTRITION = builder.defineInRange("oatPancakeNutrition", 5, 0, Integer.MAX_VALUE);
        OAT_PANCAKE_SATURATION_MOD = builder.defineInRange("oatPancakeSaturationMod", 0.6, 0.0, Double.MAX_VALUE);
        ROASTED_CORN_NUTRITION = builder.defineInRange("roastedCornNutrition", 5, 0, Integer.MAX_VALUE);
        ROASTED_CORN_SATURATION_MOD = builder.defineInRange("roastedCornSaturationMod", 0.5, 0.0, Double.MAX_VALUE);
        POTATO_WITH_ROAST_MEAT_NUTRITION = builder.defineInRange("potatoWithRoastMeatNutrition", 7, 0, Integer.MAX_VALUE);
        POTATO_WITH_ROAST_MEAT_SATURATION_MOD = builder.defineInRange("potatoWithRoastMeatSaturationMod", 0.7, 0.0, Double.MAX_VALUE);
        BAKED_LAMB_HAM_NUTRITION = builder.defineInRange("bakedLambHamNutrition", 8, 0, Integer.MAX_VALUE);
        BAKED_LAMB_HAM_SATURATION_MOD = builder.defineInRange("bakedLambHamSaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        FARMERS_BREAKFAST_NUTRITION = builder.defineInRange("farmersBreakfastNutrition", 12, 0, Integer.MAX_VALUE);
        FARMERS_BREAKFAST_SATURATION_MOD = builder.defineInRange("farmersBreakfastSaturationMod", 1.2, 0.0, Double.MAX_VALUE);
        STUFFED_CHICKEN_NUTRITION = builder.defineInRange("stuffedChickenNutrition", 8, 0, Integer.MAX_VALUE);
        STUFFED_CHICKEN_SATURATION_MOD = builder.defineInRange("stuffedChickenSaturationMod", 0.8, 0.0, Double.MAX_VALUE);
        STUFFED_RABBIT_NUTRITION = builder.defineInRange("stuffedRabbitNutrition", 9, 0, Integer.MAX_VALUE);
        STUFFED_RABBIT_SATURATION_MOD = builder.defineInRange("stuffedRabbitSaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        GRANDMOTHERS_STRAWBERRY_CAKE_NUTRITION = builder.defineInRange("grandmothersStrawberryCakeNutrition", 4, 0, Integer.MAX_VALUE);
        GRANDMOTHERS_STRAWBERRY_CAKE_SATURATION_MOD = builder.defineInRange("grandmothersStrawberryCakeSaturationMod", 0.7, 0.0, Double.MAX_VALUE);
        FARMERS_BREAD_NUTRITION = builder.defineInRange("farmersBreadNutrition", 6, 0, Integer.MAX_VALUE);
        FARMERS_BREAD_SATURATION_MOD = builder.defineInRange("farmersBreadSaturationMod", 0.8, 0.0, Double.MAX_VALUE);
        FARMER_SALAD_NUTRITION = builder.defineInRange("farmerSaladNutrition", 7, 0, Integer.MAX_VALUE);
        FARMER_SALAD_SATURATION_MOD = builder.defineInRange("farmerSaladSaturationMod", 0.6, 0.0, Double.MAX_VALUE);
        GOULASH_NUTRITION = builder.defineInRange("goulashNutrition", 8, 0, Integer.MAX_VALUE);
        GOULASH_SATURATION_MOD = builder.defineInRange("goulashSaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        SIMPLE_TOMATO_SOUP_NUTRITION = builder.defineInRange("simpleTomatoSoupNutrition", 6, 0, Integer.MAX_VALUE);
        SIMPLE_TOMATO_SOUP_SATURATION_MOD = builder.defineInRange("simpleTomatoSoupSaturationMod", 0.6, 0.0, Double.MAX_VALUE);
        BARLEY_SOUP_NUTRITION = builder.defineInRange("barleySoupNutrition", 5, 0, Integer.MAX_VALUE);
        BARLEY_SOUP_SATURATION_MOD = builder.defineInRange("barleySoupSaturationMod", 0.8, 0.0, Double.MAX_VALUE);
        ONION_SOUP_NUTRITION = builder.defineInRange("onionSoupNutrition", 7, 0, Integer.MAX_VALUE);
        ONION_SOUP_SATURATION_MOD = builder.defineInRange("onionSoupSaturationMod", 0.6, 0.0, Double.MAX_VALUE);
        POTATO_SOUP_NUTRITION = builder.defineInRange("potatoSoupNutrition", 5, 0, Integer.MAX_VALUE);
        POTATO_SOUP_SATURATION_MOD = builder.defineInRange("potatoSoupSaturationMod", 0.6, 0.0, Double.MAX_VALUE);
        PASTA_WITH_ONION_SAUCE_NUTRITION = builder.defineInRange("pastaWithOnionSauceNutrition", 6, 0, Integer.MAX_VALUE);
        PASTA_WITH_ONION_SAUCE_SATURATION_MOD = builder.defineInRange("pastaWithOnionSauceSaturationMod", 0.7, 0.0, Double.MAX_VALUE);
        CORN_GRITS_NUTRITION = builder.defineInRange("cornGritsNutrition", 6, 0, Integer.MAX_VALUE);
        CORN_GRITS_SATURATION_MOD = builder.defineInRange("cornGritsSaturationMod", 0.5, 0.0, Double.MAX_VALUE);
        OATMEAL_WITH_STRAWBERRIES_NUTRITION = builder.defineInRange("oatmealWithStrawberriesNutrition", 4, 0, Integer.MAX_VALUE);
        OATMEAL_WITH_STRAWBERRIES_SATURATION_MOD = builder.defineInRange("oatmealWithStrawberriesSaturationMod", 0.8, 0.0, Double.MAX_VALUE);
        SAUSAGE_WITH_OAT_PATTY_NUTRITION = builder.defineInRange("sausageWithOatPattyNutrition", 8, 0, Integer.MAX_VALUE);
        SAUSAGE_WITH_OAT_PATTY_SATURATION_MOD = builder.defineInRange("sausageWithOatPattySaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        LAMB_WITH_CORN_NUTRITION = builder.defineInRange("lambWithCornNutrition", 8, 0, Integer.MAX_VALUE);
        LAMB_WITH_CORN_SATURATION_MOD = builder.defineInRange("lambWithCornSaturationMod", 0.8, 0.0, Double.MAX_VALUE);
        BEEF_PATTY_WITH_VEGETABLES_NUTRITION = builder.defineInRange("beefPattyWithVegetablesNutrition", 6, 0, Integer.MAX_VALUE);
        BEEF_PATTY_WITH_VEGETABLES_SATURATION_MOD = builder.defineInRange("beefPattyWithVegetablesSaturationMod", 0.8, 0.0, Double.MAX_VALUE);
        BARLEY_PATTIES_WITH_POTATOES_NUTRITION = builder.defineInRange("barleyPattiesWithPotatoesNutrition", 5, 0, Integer.MAX_VALUE);
        BARLEY_PATTIES_WITH_POTATOES_SATURATION_MOD = builder.defineInRange("barleyPattiesWithPotatoesSaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        BACON_WITH_EGGS_NUTRITION = builder.defineInRange("baconWithEggsNutrition", 6, 0, Integer.MAX_VALUE);
        BACON_WITH_EGGS_SATURATION_MOD = builder.defineInRange("baconWithEggsSaturationMod", 0.7, 0.0, Double.MAX_VALUE);
        CHICKEN_WRAPPED_IN_BACON_NUTRITION = builder.defineInRange("chickenWrappedInBaconNutrition", 9, 0, Integer.MAX_VALUE);
        CHICKEN_WRAPPED_IN_BACON_SATURATION_MOD = builder.defineInRange("chickenWrappedInBaconSaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        COOKED_SALMON_NUTRITION = builder.defineInRange("cookedSalmonNutrition", 7, 0, Integer.MAX_VALUE);
        COOKED_SALMON_SATURATION_MOD = builder.defineInRange("cookedSalmonSaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        COOKED_COD_NUTRITION = builder.defineInRange("cookedCodNutrition", 7, 0, Integer.MAX_VALUE);
        COOKED_COD_SATURATION_MOD = builder.defineInRange("cookedCodSaturationMod", 0.9, 0.0, Double.MAX_VALUE);
        ROASTED_CHICKEN_NUTRITION = builder.defineInRange("roastedChickenNutrition", 5, 0, Integer.MAX_VALUE);
        ROASTED_CHICKEN_SATURATION_MOD = builder.defineInRange("roastedChickenSaturationMod", 0.8, 0.0, Double.MAX_VALUE);
        builder.pop();

        COMMON_CONFIG = builder.build();
    }

    public static void onLoad(ModConfigEvent.Loading event) {
        sync();
    }

    public static void onReload(ModConfigEvent.Reloading event) {
        sync();
    }

    public static void sync() {
        enableRainGrowthEffect = ENABLE_RAIN_GROWTH_EFFECT.get();
        enableFireflies = ENABLE_FIREFLIES.get();
        rainGrowthMultiplier = RAIN_GROWTH_MULTIPLIER.get();
        bigCropChance = BIG_CROP_CHANCE.get();
        enableBonemealEffect = ENABLE_BONEMEAL_EFFECT.get();
        enableFertilizer = ENABLE_FERTILIZER.get();
        fertilizedSoilRange = FERTILIZED_SOIL_RANGE.get();
        scarecrowGrowthInterval = SCARECROW_GROWTH_INTERVAL.get();
        scarecrowRange = SCARECROW_RANGE.get();
        wildCropDropChance = WILD_CROP_DROP_CHANCE.get();
        waterSprinklerRange = WATER_SPRINKLER_RANGE.get();
        wellGroundwaterDepth = WELL_GROUNDWATER_DEPTH.get();
        wellRainFillChance = WELL_RAIN_FILL_CHANCE.get();
        feedingTroughRange = FEEDING_TROUGH_RANGE.get();
        enableDogFoodTaming = ENABLE_DOG_FOOD_TAMING.get();
        enableCatTamingChance = ENABLE_CAT_TAMING_CHANCE.get();
        enableHorseTaming = ENABLE_HORSE_TAMING.get();
        enableHorseEffects = ENABLE_HORSE_EFFECTS.get();
        enableChickenEffects = ENABLE_CHICKEN_EFFECTS.get();
        chickenCoopMaxChickens = CHICKEN_COOP_MAX_CHICKENS.get();
        chickenCoopMaxEggs = CHICKEN_COOP_MAX_EGGS.get();
        enableDogBegging = ENABLE_DOG_BEGGING.get();
        enableCatBegging = ENABLE_CAT_BEGGING.get();
        petBowlSearchRange = PET_BOWL_SEARCH_RANGE.get();
        feedingTimeMiddayStart = FEEDING_TIME_MIDDAY_START.get();
        feedingTimeMiddayEnd = FEEDING_TIME_MIDDAY_END.get();
        feedingTimeEveningStart = FEEDING_TIME_EVENING_START.get();
        feedingTimeEveningEnd = FEEDING_TIME_EVENING_END.get();
        ironCleaverChops = IRON_CLEAVER_CHOPS.get();
        diamondCleaverChops = DIAMOND_CLEAVER_CHOPS.get();
        netheriteCleaverChops = NETHERITE_CLEAVER_CHOPS.get();
        cleaverHeadDrops = CLEAVER_HEAD_DROPS.get();
        cookingExperience = COOKING_EXPERIENCE.get();
        cookingExperienceMultiplier = COOKING_EXPERIENCE_MULTIPLIER.get().floatValue();
        animations = ANIMATIONS.get();
        showCuttingBoardInfo = SHOW_CUTTING_BOARD_INFO.get();
        showMincerInfo = SHOW_MINCER_INFO.get();
        showCraftingBowlInfo = SHOW_CRAFTING_BOWL_INFO.get();
        showSiloInfo = SHOW_SILO_INFO.get();
        showWaterSprinklerInfo = SHOW_WATER_SPRINKLER_INFO.get();
        showScarecrowInfo = SHOW_SCARECROW_INFO.get();
        infoTooltipsNeedDungarees = INFO_TOOLTIPS_NEED_DUNGAREES.get();
        chickenEffectTickInterval = CHICKEN_EFFECT_TICK_INTERVAL.get();
        chickenEffectEggChance = CHICKEN_EFFECT_EGG_CHANCE.get();
        chickenEffectFeatherChance = CHICKEN_EFFECT_FEATHER_CHANCE.get();
        feastEffectSatiationInterval = FEAST_EFFECT_SATIATION_INTERVAL.get();
        feastEffectSustenanceInterval = FEAST_EFFECT_SUSTENANCE_INTERVAL.get();
        feastEffectHealAmount = FEAST_EFFECT_HEAL_AMOUNT.get();
        sustenanceEffectInterval = SUSTENANCE_EFFECT_INTERVAL.get();
        sustenanceEffectHealAmount = SUSTENANCE_EFFECT_HEAL_AMOUNT.get();
        sustenanceEffectFoodIncrement = SUSTENANCE_EFFECT_FOOD_INCREMENT.get();
        satiationEffectInterval = SATIATION_EFFECT_INTERVAL.get();
        satiationEffectHealAmount = SATIATION_EFFECT_HEAL_AMOUNT.get();
        oatPancakeNutrition = OAT_PANCAKE_NUTRITION.get();
        oatPancakeSaturationMod = OAT_PANCAKE_SATURATION_MOD.get();
        roastedCornNutrition = ROASTED_CORN_NUTRITION.get();
        roastedCornSaturationMod = ROASTED_CORN_SATURATION_MOD.get();
        potatoWithRoastMeatNutrition = POTATO_WITH_ROAST_MEAT_NUTRITION.get();
        potatoWithRoastMeatSaturationMod = POTATO_WITH_ROAST_MEAT_SATURATION_MOD.get();
        bakedLambHamNutrition = BAKED_LAMB_HAM_NUTRITION.get();
        bakedLambHamSaturationMod = BAKED_LAMB_HAM_SATURATION_MOD.get();
        farmersBreakfastNutrition = FARMERS_BREAKFAST_NUTRITION.get();
        farmersBreakfastSaturationMod = FARMERS_BREAKFAST_SATURATION_MOD.get();
        stuffedChickenNutrition = STUFFED_CHICKEN_NUTRITION.get();
        stuffedChickenSaturationMod = STUFFED_CHICKEN_SATURATION_MOD.get();
        stuffedRabbitNutrition = STUFFED_RABBIT_NUTRITION.get();
        stuffedRabbitSaturationMod = STUFFED_RABBIT_SATURATION_MOD.get();
        grandmothersStrawberryCakeNutrition = GRANDMOTHERS_STRAWBERRY_CAKE_NUTRITION.get();
        grandmothersStrawberryCakeSaturationMod = GRANDMOTHERS_STRAWBERRY_CAKE_SATURATION_MOD.get();
        farmersBreadNutrition = FARMERS_BREAD_NUTRITION.get();
        farmersBreadSaturationMod = FARMERS_BREAD_SATURATION_MOD.get();
        farmerSaladNutrition = FARMER_SALAD_NUTRITION.get();
        farmerSaladSaturationMod = FARMER_SALAD_SATURATION_MOD.get();
        goulashNutrition = GOULASH_NUTRITION.get();
        goulashSaturationMod = GOULASH_SATURATION_MOD.get();
        simpleTomatoSoupNutrition = SIMPLE_TOMATO_SOUP_NUTRITION.get();
        simpleTomatoSoupSaturationMod = SIMPLE_TOMATO_SOUP_SATURATION_MOD.get();
        barleySoupNutrition = BARLEY_SOUP_NUTRITION.get();
        barleySoupSaturationMod = BARLEY_SOUP_SATURATION_MOD.get();
        onionSoupNutrition = ONION_SOUP_NUTRITION.get();
        onionSoupSaturationMod = ONION_SOUP_SATURATION_MOD.get();
        potatoSoupNutrition = POTATO_SOUP_NUTRITION.get();
        potatoSoupSaturationMod = POTATO_SOUP_SATURATION_MOD.get();
        pastaWithOnionSauceNutrition = PASTA_WITH_ONION_SAUCE_NUTRITION.get();
        pastaWithOnionSauceSaturationMod = PASTA_WITH_ONION_SAUCE_SATURATION_MOD.get();
        cornGritsNutrition = CORN_GRITS_NUTRITION.get();
        cornGritsSaturationMod = CORN_GRITS_SATURATION_MOD.get();
        oatmealWithStrawberriesNutrition = OATMEAL_WITH_STRAWBERRIES_NUTRITION.get();
        oatmealWithStrawberriesSaturationMod = OATMEAL_WITH_STRAWBERRIES_SATURATION_MOD.get();
        sausageWithOatPattyNutrition = SAUSAGE_WITH_OAT_PATTY_NUTRITION.get();
        sausageWithOatPattySaturationMod = SAUSAGE_WITH_OAT_PATTY_SATURATION_MOD.get();
        lambWithCornNutrition = LAMB_WITH_CORN_NUTRITION.get();
        lambWithCornSaturationMod = LAMB_WITH_CORN_SATURATION_MOD.get();
        beefPattyWithVegetablesNutrition = BEEF_PATTY_WITH_VEGETABLES_NUTRITION.get();
        beefPattyWithVegetablesSaturationMod = BEEF_PATTY_WITH_VEGETABLES_SATURATION_MOD.get();
        barleyPattiesWithPotatoesNutrition = BARLEY_PATTIES_WITH_POTATOES_NUTRITION.get();
        barleyPattiesWithPotatoesSaturationMod = BARLEY_PATTIES_WITH_POTATOES_SATURATION_MOD.get();
        baconWithEggsNutrition = BACON_WITH_EGGS_NUTRITION.get();
        baconWithEggsSaturationMod = BACON_WITH_EGGS_SATURATION_MOD.get();
        chickenWrappedInBaconNutrition = CHICKEN_WRAPPED_IN_BACON_NUTRITION.get();
        chickenWrappedInBaconSaturationMod = CHICKEN_WRAPPED_IN_BACON_SATURATION_MOD.get();
        cookedSalmonNutrition = COOKED_SALMON_NUTRITION.get();
        cookedSalmonSaturationMod = COOKED_SALMON_SATURATION_MOD.get();
        cookedCodNutrition = COOKED_COD_NUTRITION.get();
        cookedCodSaturationMod = COOKED_COD_SATURATION_MOD.get();
        roastedChickenNutrition = ROASTED_CHICKEN_NUTRITION.get();
        roastedChickenSaturationMod = ROASTED_CHICKEN_SATURATION_MOD.get();
    }
}
